version: 2

sources:
  - name: athena
    database: pae
    schema: public
    tables:
      - name: athena_airtable_people_todo
        description: "Raw Airtable todos table imported from Airtable conected to athena via airbyte"

      - name: athena_employees
        description: "Raw table that comes from the factorial employee tables."

      - name: athena_teams
        description: "Raw table that comes from the factorial teams tables."

      - name: athena_memberships
        description: "Raw table that comes from the factorial memberships tables."

      - name: athena_contracts_contract_versions
        description: "Raw table that comes from the factorial contracts tables."

      - name: athena_job_catalog_roles
        description: "Raw table that comes from the factorial job catalog roles tables."

      - name: athena_job_catalog_levels
        description: "Raw table that comes from the factorial job catalog levels tables."

      - name: athena_employees_performance_scores
        description: "Raw table that comes from the factorial employees performance scores tables."

      - name: athena_climate_survey_responses_v3
        description: "Raw table that comes from the factorial climate survey responses tables."

  - name: files
    database: pae
    schema: public
    tables:
      - name: file_hiring_process_2024
        description: "Uploaded file containing hiring process 2024 data from airtable."
        columns:
          - name: name
            description: "Exemple de documentació :)."

      - name: file_hiring_process_2025
        description: "Uploaded file containing hiring process 2025 data from airtable."

      - name: file_offer_letters
        description: "Uploaded file containing offer letters data from airtable."

      - name: file_manager_assessment_raw_data
        description: "Uploaded file containing managers assessment responses from google forms."


  - name: athena_performance
    database: pae
    schema: public
    tables:
    - name: athena_performance_review_processes
      description: "Raw table containing performance review process definitions imported into Athena."

    - name: athena_performance_review_process_targets
      description: "Raw table of targets/goals associated with performance review processes."

    - name: athena_performance_review_evaluations
      description: "Raw table with individual evaluation records for performance reviews."

    - name: athena_performance_review_final_employee_scores
      description: "Raw table with final aggregated employee scores from performance reviews."
      

    - name: athena_performance_review_employee_scores
      description: "Raw table with granular employee score items from performance reviews."