# Generated by Django 5.2.7 on 2025-10-28 20:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the entity", max_length=100),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the entity"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the record was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the record was last updated"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the entity is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Base Model",
                "verbose_name_plural": "Base Models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="engagement.basemodel",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(help_text="Employee's first name", max_length=50),
                ),
                (
                    "last_name",
                    models.CharField(help_text="Employee's last name", max_length=50),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Employee's email address",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["last_name", "first_name"],
            },
            bases=("engagement.basemodel",),
        ),
        migrations.CreateModel(
            name="RelatedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the related item", max_length=200
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Content of the related item"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High")],
                        default=1,
                        help_text="Priority level",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False, help_text="Whether the item is completed"
                    ),
                ),
                (
                    "base_entity",
                    models.ForeignKey(
                        help_text="Reference to the base entity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_items",
                        to="engagement.basemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Related Model",
                "verbose_name_plural": "Related Models",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
