# Generated by Django 5.2.7 on 2025-10-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='job_title',
            field=models.CharField(blank=True, help_text='Job title for this contract', max_length=150, null=True),
        ),
    ]
