# Generated by Django 5.2.7 on 2025-10-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basemodel",
            name="factorial_id",
            field=models.CharField(
                blank=True,
                help_text="Factorial ID of the entity",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="basemodel",
            name="tair_id",
            field=models.CharField(
                blank=True,
                help_text="Tair ID of the entity",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
