# Generated by Django 5.2.7 on 2025-10-28 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0002_basemodel_factorial_id_basemodel_tair_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="engagement.basemodel",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(help_text="Name of the team", max_length=100),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[("team", "Team"), ("market", "Market")],
                        default="team",
                        help_text="Whether this is a team or market",
                        max_length=10,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        help_text="Organizational level (1 = top level, higher numbers = deeper in hierarchy)",
                    ),
                ),
                (
                    "parent_team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent team in the organizational hierarchy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_teams",
                        to="engagement.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "ordering": ["level", "team_name"],
                "unique_together": {("team_name", "parent_team")},
            },
            bases=("engagement.basemodel",),
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        help_text="Date when the membership becomes effective"
                    ),
                ),
                (
                    "effective_to",
                    models.DateField(help_text="Date when the membership ends"),
                ),
                (
                    "is_lead",
                    models.BooleanField(
                        default=False, help_text="Whether this member is a team leader"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee who is a member of the team",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="engagement.employee",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        help_text="Team the employee belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="engagement.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team Membership",
                "verbose_name_plural": "Team Memberships",
                "ordering": ["-effective_from", "team__team_name", "employee__last_name"],
                "unique_together": {("employee", "team", "effective_from")},
            },
        ),
    ]
