# Generated by Django 5.2.7 on 2025-11-03 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_contract_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorial_id', models.CharField(blank=True, help_text='Factorial ID of the entity', max_length=100, null=True, unique=True)),
                ('tair_id', models.CharField(blank=True, help_text='Tair ID of the entity', max_length=100, null=True, unique=True)),
                ('name', models.CharField(help_text='Name of the entity', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the entity')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the record was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the entity is active')),
                ('performance_name', models.CharField(help_text='Name or title of the performance review', max_length=200)),
                ('performance_date', models.DateField(help_text='Date of the performance review')),
                ('overall_score', models.PositiveIntegerField(blank=True, help_text='Score given during the performance review', null=True)),
                ('manager_questionary', models.TextField(blank=True, help_text="Manager's responses to the performance review questions", null=True)),
                ('self_questionary', models.TextField(blank=True, help_text="Employee's responses to the performance review questions", null=True)),
                ('employee', models.ForeignKey(help_text='Employee associated with this performance review', on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='engagement.employee')),
            ],
            options={
                'verbose_name': 'Performance Review',
                'verbose_name_plural': 'Performance Reviews',
                'ordering': ['-performance_date'],
            },
        ),
    ]
