# Generated by Django 5.2.7 on 2025-11-03 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_performancereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Manager who conducted the performance review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_performance_reviews', to='engagement.employee'),
        ),
    ]
