# Generated by Django 5.2.7 on 2025-10-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0003_team_teammembership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="level",
            field=models.IntegerField(
                blank=True,
                help_text="Organizational level (1 = top level, higher numbers = deeper in hierarchy)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="nature",
            field=models.CharField(
                choices=[("team", "Team"), ("market", "Market"), ("office", "Office")],
                default="team",
                help_text="Whether this is a team or market",
                max_length=10,
            ),
        ),
    ]
