# Generated by Django 5.2.7 on 2025-11-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_performancereview_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='offboarding_date',
            field=models.DateField(blank=True, help_text='Date when the employee was offboarded', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='onboarding_date',
            field=models.DateField(blank=True, help_text='Date when the employee was onboarded', null=True),
        ),
    ]
