# Generated by Django 5.2.7 on 2025-10-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0004_alter_team_level_alter_team_nature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammembership",
            name="effective_from",
            field=models.DateField(
                blank=True,
                help_text="Date when the membership becomes effective",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="effective_to",
            field=models.DateField(
                blank=True, help_text="Date when the membership ends", null=True
            ),
        ),
    ]
