# Generated by Django 5.2.7 on 2025-11-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_employee_offboarding_date_employee_onboarding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancereview',
            name='self_score',
            field=models.PositiveIntegerField(blank=True, help_text='Score given by the employee in self-assessment', null=True),
        ),
    ]
