# Generated by Django 5.2.7 on 2025-11-27 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sql_query', models.TextField(help_text='SQL query to execute')),
                ('database', models.CharField(choices=[('trino', 'Trino'), ('sqlite', 'SQLite')], default='trino', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Queries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(default=dict, help_text="\n        Stores: {\n            'title': str,\n            'thresholds': {'red': float, 'yellow': float},\n            'dimensionFilters': {},\n            'dimensionExcludes': {},\n            'enabledFilters': {},\n            'metricRanges': {},\n            'aggMetricRanges': {},\n            'visibleColumns': [],\n            'selectedDimensions': [],\n            'sortConfig': {'column': str, 'direction': str}\n        }\n        ")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_query_views', to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='queries.query')),
            ],
            options={
                'verbose_name_plural': 'Query Views',
                'ordering': ['-updated_at'],
            },
        ),
    ]
