with raw_airtable_todos as (
    select * from {{ source("athena", "airbyte_airtable_people_people_todos_sync_view_tblmwfnk5fykznky7") }}
)

select 
    CAST(id_empleado AS BIGINT) as employee_id,
    benefits,
    come_back,
    main_team,
    "a&r_comments" as ar_comments,
    compensation,
    job_position,
    "t&c_comments" as tc_comments,
    manager_email,
    team_comments,
    market_specific,
    culture_comments,
    manager_comments,
    product_comments,
    benefits_comments,
    factorial_product,
    fecha_offboarding,
    rate_team_members,
    rate_your_manager,
    terminated_reason,
    "work-life_balance" as work_life_balance,
    "días_en_la_empresa" as days_in_company,
    "prof._dev._comments" as professional_development_comments,
    "afterworks_&_rituals" as afterworks_and_rituals,
    "permanencia_(months)" as permanence_months,
    rate_overall_culture,
    room_for_improvement,
    "w-l_balance_comments" as work_life_balance_comments,
    "where_are_you_going?" as where_are_you_going,
    compensation_comments,
    most_positive_aspects,
    recommend_to_a_friend,
    main_reason_of_leaving,
    come_back_circumstances,
    professional_development,
    tipo_de_baja_simplificada,
    "is_your_salary_increasing?" as is_salary_increasing,
    comment_reasons_for_leaving,
    secondary_reason_of_leaving,
    "transparency_&_communication" as transparency_and_communication
from raw_airtable_todos
